#!/bin/bash
#
# MATHUSLA Tracker : Build Script
#
# Copyright 2018 Brandon Gomes
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

CONFIG_CMAKE=0
CLEAN_BUILD=0
RUN_BUILD=0
PASS_HELP=0
declare -a OTHER_ARGS
OTHER_ARGS_INDEX=0

while [[ $# -gt 0 ]]; do
    arg="$1"
    case $arg in
        --cmake | cmake) CONFIG_CMAKE=1
            shift;;
        --clean | clean) CLEAN_BUILD=1
            shift;;
        --run | run) RUN_BUILD=1
            shift;;
        --help | help | -h)
            if [[ RUN_BUILD -eq 0 ]]; then
              echo -e "usage: ./install [--clean] [--cmake] [--run [args]]"
              echo -e "  clean      : rebuild all source files"
              echo -e "  cmake      : rebuild with CMake"
              echo -e "  run [args] : run executable after building with \"args\""
              echo -e "  help       : open this help screen"
              exit
            fi
            PASS_HELP=1
            shift;;
        *) OTHER_ARGS[OTHER_ARGS_INDEX++]="$arg"
            shift;;
    esac
done


if [[ "$CONFIG_CMAKE" -eq 1 && "$CLEAN_BUILD" -eq 1 ]]; then
    rm -rf build;
fi

if [ ! -d "build" ]; then
    mkdir -p build
    CONFIG_CMAKE=1
    CLEAN_BUILD=1
fi

cd build

if [[ "$CONFIG_CMAKE" -eq 1 ]]; then
    cmake .. -DCMAKE_INSTALL_PREFIX=../.temp/tracker-install/ -DCMAKE_BUILD_TYPE=Release
fi
if [[ "$CLEAN_BUILD"  -eq 1 ]]; then make clean; fi;

make -j8

if [[ ! "$?" -eq 0 ]]; then
    echo -e "\nBuild Failed!\n"
else
    if [[ "$RUN_BUILD" -eq 1 ]]; then
        cd ..;
        NAME=${OTHER_ARGS[0]}
        unset OTHER_ARGS[0]
        ARGS=${OTHER_ARGS[*]}
        if [[ PASS_HELP -eq 1 ]]; then ARGS="--help"; fi
        case $NAME in
          prototype)  ./build/demo/prototype/prototype   ${ARGS}; ;;
          box)        ./build/demo/box/box               ${ARGS}; ;;
          module_box) ./build/demo/module_box/module_box ${ARGS}; ;;
          *) echo -e "ERROR: No Project Named: $NAME"; ;;
        esac
    fi;
fi
